service:
  name: live-chat-server

provider:
  name: aws
  profile: personal
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions: ${file(ymls/functions.yml)}

plugins:
  - serverless-offline