service:
  name: live-chat-server

provider:
  name: aws
  profile: personal
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  createUser:
    handler: services/users/handler.create
    events:
      - http:
          path: users/create
          method: get
          cors: true

plugins:
  - serverless-offline